import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
import { DateTime } from 'luxon'

export default class GeneralItemsSeeder extends BaseSeeder {
  async run() {
    await db.from('general_items').delete()
    const now = DateTime.now().toSQL()

    await db.table('general_items').multiInsert([
      // --- ACESSÓRIOS ---
      {
        name: 'Kit de Perícia',
        category: 0,
        type: 'Acessório',
        spaces: 1,
        description: 'Um conjunto de ferramentas necessárias para algumas perícias ou usos de perícias. Sem o kit, você sofre –5 no teste. Existe um kit de perícia para cada perícia que exige este item.',
        created_at: now,
      },
      {
        name: 'Utensílio',
        category: 1,
        type: 'Acessório',
        spaces: 1,
        description: 'Um item comum que tenha uma utilidade específica, como um canivete, uma lupa, um smartphone ou um notebook. Um utensílio fornece +2 em uma perícia (exceto Luta e Pontaria). Precisa ser empunhado para que o bônus seja aplicado.',
        created_at: now,
      },
      {
        name: 'Vestimenta',
        category: 1,
        type: 'Acessório',
        spaces: 1,
        description: 'Uma peça de vestuário que fornece +2 em uma perícia (exceto Luta ou Pontaria). Você pode receber os bônus de no máximo duas vestimentas ao mesmo tempo. Vestir ou despir uma vestimenta é uma ação completa.',
        created_at: now,
      },

      // --- EXPLOSIVOS ---
      {
        name: 'Granada de Atordoamento',
        category: 0,
        type: 'Explosivo',
        spaces: 1,
        description: 'Também chamadas de flash-bang, por criarem um estouro barulhento e luminoso. Seres na área ficam atordoados por 1 rodada (Fortitude DT Agi reduz para ofuscado e surdo por uma rodada).',
        created_at: now,
      },
      {
        name: 'Granada de Fragmentação',
        category: 1,
        type: 'Explosivo',
        spaces: 1,
        description: 'Espalha fragmentos perfurantes. Seres na área sofrem 8d6 pontos de dano de perfuração (Reflexos DT Agi reduz à metade).',
        created_at: now,
      },
      {
        name: 'Granada de Fumaça',
        category: 0,
        type: 'Explosivo',
        spaces: 1,
        description: 'Produz uma fumaça espessa e escura. Seres na área ficam cegos e sob camuflagem total. A fumaça dura 2 rodadas.',
        created_at: now,
      },
      {
        name: 'Granada Incendiária',
        category: 1,
        type: 'Explosivo',
        spaces: 1,
        description: 'Espalha labaredas incandescentes. Seres na área sofrem 6d6 pontos de dano de fogo e ficam em chamas (Reflexos DT Agi reduz o dano à metade e evita a condição em chamas).',
        created_at: now,
      },
      {
        name: 'Mina Antipessoal',
        category: 1,
        type: 'Explosivo',
        spaces: 1,
        description: 'Ativada por controle remoto. Ao explodir, dispara centenas de bolas de aço em um cone de 6m, causando 12d6 pontos de dano de perfuração em todos os seres na área (Reflexos DT Int reduz à metade). Instalar a mina exige uma ação completa e teste de Tática DT 15.',
        created_at: now,
      },

      // --- ITENS OPERACIONAIS ---
      {
        name: 'Algemas',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Um par de algemas de aço. Para prender uma pessoa que não esteja indefesa você precisa empunhar a algema, agarrar a pessoa e então vencer um novo teste de agarrar. Escapar exige teste de Acrobacia DT 30.',
        created_at: now,
      },
      {
        name: 'Arpéu',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Um gancho de aço que pode ser amarrado na ponta de uma corda para se fixar em muros, janelas, parapeitos. Prender um arpéu exige teste de Pontaria DT 15. Subir um muro com a ajuda de uma corda fornece +5 no teste de Atletismo.',
        created_at: now,
      },
      {
        name: 'Bandoleira',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Um cinto com bolsos e alças. Uma vez por rodada, você pode sacar ou guardar um item em seu inventário como uma ação livre.',
        created_at: now,
      },
      {
        name: 'Binóculos',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Estes binóculos militares fornecem +5 em testes de Percepção para observar coisas distantes.',
        created_at: now,
      },
      {
        name: 'Bloqueador de Sinal',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Este dispositivo compacto emite ondas que "poluem" a frequência de rádio usada por celulares, impedindo que qualquer aparelho desse tipo em alcance médio se conecte.',
        created_at: now,
      },
      {
        name: 'Cicatrizante',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Um spray com um remédio de potente efeito cicatrizante. Você pode gastar uma ação padrão e este item para curar 2d8+2 PV em você ou em um ser adjacente.',
        created_at: now,
      },
      {
        name: 'Corda',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Um rolo com 10 metros de corda resistente. Fornece +5 em testes de Atletismo para escalar e tem diversas outras utilidades.',
        created_at: now,
      },
      {
        name: 'Equipamento de Sobrevivência',
        category: 0,
        type: 'Operacional',
        spaces: 2,
        description: 'Uma mochila com saco de dormir, panelas, GPS e outros itens. Fornece +5 em testes de Sobrevivência para acampar e orientar-se e permite que você faça esses testes sem treinamento.',
        created_at: now,
      },
      {
        name: 'Lanterna Tática',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Ilumina um cone de 9m. Você pode gastar uma ação de movimento para mirar a luz nos olhos de um ser em alcance curto. Ele fica ofuscado por 1 rodada, mas imune à lanterna pelo resto da cena.',
        created_at: now,
      },
      {
        name: 'Máscara de Gás',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Uma máscara com filtro que cobre o rosto inteiro. Fornece +10 em testes de Fortitude contra efeitos que dependam de respiração.',
        created_at: now,
      },
      {
        name: 'Mochila Militar',
        category: 1,
        type: 'Operacional',
        spaces: 0,
        description: 'Uma mochila leve e de alta qualidade. Ela não usa nenhum espaço e aumenta sua capacidade de carga em 2 espaços.',
        created_at: now,
      },
      {
        name: 'Óculos de Visão Térmica',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Estes óculos eliminam a penalidade em testes por camuflagem.',
        created_at: now,
      },
      {
        name: 'Pé de Cabra',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Esta barra de ferro fornece +5 em testes de Força para arrombar portas. Pode ser usada em combate como um bastão.',
        created_at: now,
      },
      {
        name: 'Pistola de Dardos',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Dispara dardos com sonífero em alcance curto. Se acertar, o alvo fica inconsciente até o fim da cena (Fortitude DT Agi reduz para desprevenido e lento por uma rodada). Vem com 2 dardos.',
        created_at: now,
      },
      {
        name: 'Pistola Sinalizadora',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Dispara um sinalizador luminoso útil para se localizar. Pode ser usada como arma com alcance curto que causa 2d6 de dano de fogo. Vem com 2 cargas.',
        created_at: now,
      },
      {
        name: 'Soqueira',
        category: 0,
        type: 'Operacional',
        spaces: 1,
        description: 'Peça de metal usada entre os dedos que fornece +1 em rolagens de dano desarmado e os torna letal. Pode receber modificações e maldições de armas corpo a corpo.',
        created_at: now,
      },
      {
        name: 'Spray de Pimenta',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Dispara um composto químico que causa dor e lacrimação. Gaste uma ação padrão para atingir um ser adjacente. O ser fica cego por 1d4 rodadas (Fortitude DT Agi evita). Dura dois usos.',
        created_at: now,
      },
      {
        name: 'Taser',
        category: 1,
        type: 'Operacional',
        spaces: 1,
        description: 'Dispositivo de eletrochoque. Gaste uma ação padrão para atingir um ser adjacente. Ele sofre 1d6 de dano de eletricidade e fica atordoado por uma rodada (Fortitude DT Agi evita). Dura dois usos.',
        created_at: now,
      },
      {
        name: 'Traje Hazmat',
        category: 1,
        type: 'Operacional',
        spaces: 2,
        description: 'Roupa impermeável que cobre o corpo inteiro, usada para impedir contato com materiais tóxicos. Fornece +5 em testes contra efeitos ambientais e resistência a químico 10.',
        created_at: now,
      },

      // --- ITENS PARANORMAIS ---
      {
        name: 'Amarras de (Elemento)',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Cordas ou correntes feitas de um elemento paranormal. Podem ser usadas como Armadilha (ação completa + 2 PE, imobiliza criaturas vulneráveis que cruzem área 3x3m, Reflexos DT Int) ou para Laçar (ação padrão + 1 PE, paralisa até início do próximo turno do alvo, Vontade DT Agi). Manter laço custa 1 PE/rodada.',
        created_at: now,
      },
      {
        name: 'Câmera de Aura Paranormal',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Câmera amaldiçoada com Energia e sigilos de Conhecimento. Tirar uma foto gasta ação padrão e 1 PE. As fotos revelam auras paranormais em pessoas e objetos, com a cor associada ao elemento.',
        created_at: now,
      },
      {
        name: 'Componentes Ritualísticos de (Elemento)',
        category: 0,
        type: 'Paranormal',
        spaces: 1,
        description: 'Conjunto de objetos para rituais de um elemento (Sangue, Morte, Conhecimento ou Energia). Necessários para conjuração de rituais do elemento correspondente. Energia: eletricidade, pólvora, moedas. Sangue: órgãos, sangue, arame. Morte: ossos, cinzas, areia. Conhecimento: escrituras, ouro, cristais.',
        created_at: now,
      },
      {
        name: 'Emissor de Pulsos Paranormais',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Pequena caixa coberta de sigilos usada como isca de criaturas paranormais. Ativar gasta ação completa e 1 PE. Emite pulso de um elemento definido pelo ativador, atraindo criaturas do mesmo elemento e afastando as do oposto (Vontade DT Pre evita).',
        created_at: now,
      },
      {
        name: 'Escuta de Ruídos Paranormais',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Microfone que capta ruídos paranormais. Ativar gasta ação completa e 2 PE; grava por até 24 horas. Ouvir a gravação fornece +5 em testes de Ocultismo para identificar criaturas.',
        created_at: now,
      },
      {
        name: 'Medidor de Estabilidade da Membrana',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Dispositivo complexo com múltiplos medidores. Agentes treinados em Ocultismo podem usá-lo para avaliar o estado da Membrana em uma área, indicando a chance de manifestação de entidades. Não fornece respostas definitivas.',
        created_at: now,
      },
      {
        name: 'Scanner de Manifestação Paranormal de (Elemento)',
        category: 2,
        type: 'Paranormal',
        spaces: 1,
        description: 'Dispositivo conectado a objetos amaldiçoados de uma entidade, adornado com sigilos. Ativar é ação padrão. Consome 1 PE/rodada do usuário, que sempre sabe a direção de todas as manifestações do elemento escolhido em alcance longo.',
        created_at: now,
      },
    ])
  }
}
