import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
import { DateTime } from 'luxon'

export default class WeaponModificationsSeeder extends BaseSeeder {
  async run() {
    await db.from('weapon_modifications').delete()
    const now = DateTime.now().toSQL()
    
    const mods = [
      // --- MELHORIAS ---
      {
        name: 'Alongada',
        category: 1,
        type: 'Melhoria',
        description: 'Com um cano mais longo, que aumenta a precisão dos disparos, a arma fornece +2 nos testes de ataque.',
        attack_bonus: 2,
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Calibre Grosso',
        category: 1,
        type: 'Melhoria',
        description: 'A arma é modificada para disparar munição de maior calibre, aumentando seu dano em mais um dado do mesmo tipo. Por exemplo, um revólver de calibre grosso causa 3d6 de dano. Requer munição específica de calibre grosso.',
        damage_bonus: null,
        special_properties: JSON.stringify({ extra_die: 1 }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Certeira',
        category: 1,
        type: 'Melhoria',
        description: 'Fabricada para ser mais precisa e balanceada, a arma fornece +2 nos testes de ataque.',
        attack_bonus: 2,
        weapon_type_restriction: null,
        created_at: now,
      },
      {
        name: 'Compensador',
        category: 1,
        type: 'Melhoria',
        description: 'Apenas para armas automáticas. Um sistema de amortecimento reduz o coice da arma, anulando a penalidade em testes de ataque por disparar rajadas.',
        special_properties: JSON.stringify({ cancels_burst_penalty: true }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Cruel',
        category: 1,
        type: 'Melhoria',
        description: 'A arma possui lâmina especialmente afiada ou foi fabricada com materiais mais densos. Fornece um bônus de +2 nas rolagens de dano.',
        damage_bonus: '+2',
        weapon_type_restriction: null,
        created_at: now,
      },
      {
        name: 'Discreta',
        category: 1,
        type: 'Melhoria',
        description: 'A arma possui modificações para ocupar menos espaço e chamar menos atenção. Reduz o número de espaços ocupados em 1, fornece +5 em testes de Crime para ser ocultada e permite fazer esse teste mesmo sem ser treinado na perícia.',
        special_properties: JSON.stringify({ crime_bonus: 5, space_reduction: 1, untrained_crime: true }),
        spaces: -1,
        weapon_type_restriction: null,
        created_at: now,
      },
      {
        name: 'Dum-Dum',
        category: 1,
        type: 'Melhoria',
        description: 'Balas feitas para se expandir durante o impacto, produzindo ferimentos terríveis. Aumenta o multiplicador de crítico em +1. Apenas para balas curtas e longas.',
        critical_multiplier_bonus: '+1x',
        critical_bonus: null,
        weapon_type_restriction: JSON.stringify(['Balas Curtas', 'Balas Longas']),
        created_at: now,
      },
      {
        name: 'Explosiva',
        category: 1,
        type: 'Melhoria',
        description: 'Munições com uma gota de mercúrio ou glicerina que fazem a bala explodir ao atingir o alvo. Aumenta o dano causado em +2d6. Apenas para cartuchos.',
        damage_bonus: '+2d6',
        weapon_type_restriction: JSON.stringify(['Cartuchos']),
        created_at: now,
      },
      {
        name: 'Ferrolho Automático',
        category: 1,
        type: 'Melhoria',
        description: 'O mecanismo de ação da arma é modificado para disparar várias vezes em sequência. A arma se torna automática.',
        special_properties: JSON.stringify({ automatic: true }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Mira Laser',
        category: 1,
        type: 'Melhoria',
        description: 'Um laser interno cria um reflexo vermelho num retículo luminoso, ajudando a realizar disparos mais letais. Aumenta a margem de ameaça em +2.',
        critical_bonus: 2,
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Mira Telescópica',
        category: 1,
        type: 'Melhoria',
        description: 'A arma possui uma luneta com marcações de medidas, ideal para disparos precisos de longa distância. Aumenta o alcance da arma em uma categoria e permite que a habilidade Ataque Furtivo seja usada em qualquer alcance.',
        range_bonus: 1,
        special_properties: JSON.stringify({ sneak_attack_any_range: true }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Perigosa',
        category: 1,
        type: 'Melhoria',
        description: 'A arma possui lâmina afiada como uma navalha ou foi fabricada com materiais maciços. Seus golpes possuem impacto terrível. Aumenta a margem de ameaça em +2.',
        critical_bonus: 2,
        weapon_type_restriction: null,
        created_at: now,
      },
      {
        name: 'Silenciador',
        category: 1,
        type: 'Melhoria',
        description: 'Um silenciador reduz em -10 a penalidade em Furtividade para se esconder no mesmo turno em que atacou com a arma de fogo.',
        special_properties: JSON.stringify({ stealth_penalty_reduction: 10 }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },
      {
        name: 'Tática',
        category: 1,
        type: 'Melhoria',
        description: 'A arma possui cabo texturizado, bandoleira e outros acessórios que facilitam seu manuseio. Você pode sacar a arma como uma ação livre.',
        special_properties: JSON.stringify({ free_draw: true }),
        weapon_type_restriction: null,
        created_at: now,
      },
      {
        name: 'Visão de Calor',
        category: 1,
        type: 'Melhoria',
        description: 'A mira tem um sistema eletrônico que sobrepõe imagens visíveis e em infravermelho. Ao disparar com a arma, você ignora qualquer camuflagem do alvo.',
        special_properties: JSON.stringify({ ignores_camouflage: true }),
        weapon_type_restriction: JSON.stringify(['Arma de fogo']),
        created_at: now,
      },

      // --- MALDIÇÕES ---
      // CONHECIMENTO
      {
        name: 'Antielemento',
        category: 2,
        type: 'Maldição',
        element: 'Conhecimento',
        description: 'Letal contra criaturas de um elemento. Gaste 2 PE e acerte o ataque para causar +4d8 de dano.',
        created_at: now,
      },
      {
        name: 'Ritualística',
        category: 2,
        type: 'Maldição',
        element: 'Conhecimento',
        description: 'Armazena um ritual na arma para ser descarregado como ação livre ao acertar um ataque.',
        created_at: now,
      },
      {
        name: 'Senciente',
        category: 4,
        type: 'Maldição',
        element: 'Conhecimento',
        description: 'A arma flutua e ataca por conta própria. Custo: 2 PE para imbuir + 1 PE por turno para manter.',
        created_at: now,
      },
      // ENERGIA
      {
        name: 'Empuxo',
        category: 2,
        type: 'Maldição',
        element: 'Energia',
        description: 'A arma pode ser arremessada, causa +1 dado de dano e volta voando para você. (Corpo a corpo apenas)',
        special_properties: JSON.stringify({ throwable: true, throwExtraDice: true }),
        created_at: now,
      },
      {
        name: 'Energética',
        category: 2,
        type: 'Maldição',
        element: 'Energia',
        description: 'Gaste 2 PE para converter o dano em Energia. Fornece +5 no ataque e ignora RD.',
        created_at: now,
      },
      {
        name: 'Vibrante',
        category: 2,
        type: 'Maldição',
        element: 'Energia',
        description: 'Recebe Ataque Extra. Se já tiver, o custo da habilidade diminui em -1 PE.',
        created_at: now,
      },
      // MORTE
      {
        name: 'Consumidora',
        category: 2,
        type: 'Maldição',
        element: 'Morte',
        description: 'Drena entropia. Gaste 2 PE para deixar o alvo imóvel por uma rodada ao acertar.',
        created_at: now,
      },
      {
        name: 'Erosiva',
        category: 2,
        type: 'Maldição',
        element: 'Morte',
        description: 'Acelera o envelhecimento: +1d8 de dano de Morte. Gaste 2 PE por 2d4 de dano extra por 2 rodadas.',
        created_at: now,
      },
      {
        name: 'Repulsora',
        category: 2,
        type: 'Maldição',
        element: 'Morte',
        description: 'Aura que fornece +2 de Defesa. Ao bloquear, gaste 2 PE para ganhar +5 adicional na Defesa.',
        created_at: now,
      },
      // SANGUE
      {
        name: 'Lancinante',
        category: 2,
        type: 'Maldição',
        element: 'Sangue',
        description: 'Ferimentos terríveis: +1d8 de dano de Sangue (multiplicado em críticos).',
        created_at: now,
      },
      {
        name: 'Predadora',
        category: 2,
        type: 'Maldição',
        element: 'Sangue',
        description: 'Anula penalidades por camuflagem/cobertura leves, aumenta alcance em uma categoria e duplica a margem de ameaça.',
        created_at: now,
      },
      {
        name: 'Sanguinária',
        category: 2,
        type: 'Maldição',
        element: 'Sangue',
        description: 'Causa sangramento cumulativo. Críticos drenam sangue (alvo fraco + 2d10 PV temporários).',
        created_at: now,
      },
    ]

    await db.table('weapon_modifications').multiInsert(mods)
    console.log(`✅ ${mods.length} modificações (Melhorias e Maldições) inseridas com sucesso!`)
  }
}
