import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'
import { DateTime } from 'luxon'

/**
 * Limpa tabelas que referenciam weapons (por causa de FK) e depois repopula weapons
 * com dados oficiais: alcance indefinido = Corpo a corpo, margem de crítico indefinida = 20.
 */
    // Limpa tabela existente
    await db.from('weapons').delete()

export default class WeaponsSeeder extends BaseSeeder {
  async run() {
    const now = DateTime.now().toSQL()

    // 1. Limpar tabelas que referenciam weapons (ordem por FK)
    await db.from('character_weapon_modifications').delete()
    await db.from('character_weapons').delete()
    await db.from('weapons').delete()

    // 2. Inserir armas com estatísticas e descrições corretas
    const weapons = [
      // ========== ARMAS SIMPLES ==========
      {
        name: 'Coronhada',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d4/1d6',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 0,
        description:
          'Um golpe com a coronha de uma arma de fogo. Usa o dano 1d4 para pistolas/revólveres e 1d6 para armas longas.',
        special: null,
      },
      {
        name: 'Faca',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d4',
        damage_type: 'Corte',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Uma lâmina afiada, como uma navalha, uma faca de churrasco ou uma faca militar. É uma arma ágil e pode ser arremessada.',
        special: null,
      },
      {
        name: 'Martelo',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d6',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Esta ferramenta comum pode ser usada como arma na falta de opções melhores.',
        special: null,
      },
      {
        name: 'Punhal',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d4',
        damage_type: 'Perfuração',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Uma faca de lâmina longa e pontiaguda, usada por cultistas. É uma arma ágil.',
        special: null,
      },
      {
        name: 'Bastão',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d6/1d8',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Um cilindro de madeira maciça. Pode ser um taco de beisebol, um cassetete da polícia, uma tonfa ou apenas uma clava envolta em pregos ou arame farpado. Você pode empunhar um bastão com uma mão (dano 1d6) ou com as duas (dano 1d8).',
        special: null,
      },
      {
        name: 'Machete',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d6',
        damage_type: 'Corte',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Uma lâmina longa e larga, muito usada como ferramenta para abrir trilhas.',
        special: null,
      },
      {
        name: 'Lança',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d6',
        damage_type: 'Perfuração',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Uma haste de madeira com uma ponta metálica afiada, a lança é uma arma arcaica. Pode ser arremessada.',
        special: null,
      },
      {
        name: 'Cajado',
        category: 0,
        type: 'Simples',
        weapon_type: 'Corpo a corpo',
        damage: '1d6/1d6',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Um cabo de madeira ou barra de ferro longos. Inclui o bo usado em artes marciais. É uma arma ágil. Além disso, pode ser usado com Combater com Duas Armas para fazer ataques adicionais, como se fosse uma arma de uma mão e uma arma leve.',
        special: null,
      },
      {
        name: 'Arco',
        category: 0,
        type: 'Simples',
        weapon_type: 'Disparo',
        damage: '1d6',
        damage_type: 'Perfuração',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Um arco e flecha comum, próprio para tiro ao alvo.',
        special: null,
      },
      {
        name: 'Besta',
        category: 0,
        type: 'Simples',
        weapon_type: 'Disparo',
        damage: '1d8',
        damage_type: 'Perfuração',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Esta arma da antiguidade exige uma ação de movimento para ser recarregada a cada disparo.',
        special: null,
      },
      {
        name: 'Pistola',
        category: 1,
        type: 'Simples',
        weapon_type: 'Arma de fogo',
        damage: '1d12',
        damage_type: 'Balístico',
        critical: '18',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Uma arma de mão comum entre policiais e militares por ser facilmente recarregável.',
        special: null,
      },
      {
        name: 'Revólver',
        category: 1, // Categoria I
        type: 'Simples',
        weapon_type: 'Arma de fogo',
        damage: '2d6',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'A arma de fogo mais comum, e uma das mais confiáveis.',
        special: null,
      },
      {
        name: 'Fuzil de Caça',
        category: 1, // Categoria I
        type: 'Simples',
        weapon_type: 'Arma de fogo',
        damage: '2d8',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Esta arma de fogo é bastante popular entre fazendeiros, caçadores e atiradores esportistas.',
        special: null,
      },

      // ========== ARMAS TÁTICAS ==========
      {
        name: 'Machadinha',
        category: 0,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d6',
        damage_type: 'Corte',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Ferramenta útil para cortar madeira. Pode ser arremessada.',
        special: null,
      },
      {
        name: 'Nunchaku',
        category: 0,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d8',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Dois bastões curtos de madeira ligados por uma corrente. É uma arma ágil.',
        special: null,
      },
      {
        name: 'Corrente',
        category: 0,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d8',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Um pedaço de corrente grossa pode ser usado como uma arma bastante efetiva. A corrente fornece +2 em testes para desarmar e derrubar.',
        special: null,
      },
      {
        name: 'Espada',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d8/1d10',
        damage_type: 'Corte',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Uma arma medieval, como uma espada longa dos cavaleiros europeus ou uma cimitarra sarracena. Você pode empunhar uma espada com uma mão (dano 1d8) ou com as duas (dano 1d10).',
        special: null,
      },
      {
        name: 'Florete',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d6',
        damage_type: 'Corte',
        critical: '18',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Esta espada de lâmina fina e comprida é usada por esgrimistas. É uma arma ágil.',
        special: null,
      },
      {
        name: 'Machado',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d8',
        damage_type: 'Corte',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Uma ferramenta importante para lenhadores e bombeiros, pode causar ferimentos terríveis.',
        special: null,
      },
      {
        name: 'Maça',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '2d4',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Bastão com uma cabeça metálica cheia de protuberâncias.',
        special: null,
      },
      {
        name: 'Acha',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d12',
        damage_type: 'Corte',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description: 'Um machado grande e pesado, usado no corte de árvores largas.',
        special: null,
      },
      {
        name: 'Gadanho',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '2d4',
        damage_type: 'Corte',
        critical: '20',
        critical_multiplier: 'x4',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Uma ferramenta agrícola, o gadanho é uma versão maior da foice, para uso com as duas mãos.',
        special: null,
      },
      {
        name: 'Katana',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '1d10',
        damage_type: 'Corte',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Originária do Japão, esta espada longa e levemente curvada transcendeu os séculos. É uma arma ágil. Se você for veterano em Luta pode usá-la como uma arma de uma mão.',
        special: null,
      },
      {
        name: 'Marreta',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '3d4',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Normalmente usada para demolir paredes. Use estas estatísticas para outras ferramentas de construção civil.',
        special: null,
      },
      {
        name: 'Montante',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '2d6',
        damage_type: 'Corte',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description: 'Enorme e pesada, esta espada de 1,5m de comprimento foi uma das armas mais poderosas em seu tempo.',
        special: null,
      },
      {
        name: 'Motosserra',
        category: 1,
        type: 'Tático',
        weapon_type: 'Corpo a corpo',
        damage: '3d6',
        damage_type: 'Corte',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Uma ferramenta capaz de causar ferimentos profundos; sempre que rolar um 6 em um dado de dano, role um dado de dano adicional. É desajeitada e impõe –2d nos testes de ataque. Ligar a motosserra gasta uma ação de movimento.',
        special: null,
      },
      {
        name: 'Arco Composto',
        category: 1,
        type: 'Tático',
        weapon_type: 'Disparo',
        damage: '1d10',
        damage_type: 'Perfuração',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Este arco moderno usa materiais de alta tensão e um sistema de roldanas para gerar mais pressão. Ao contrário de outras armas de disparo, permite que você aplique seu valor de Força às rolagens de dano.',
        special: null,
      },
      {
        name: 'Balestra',
        category: 1,
        type: 'Tático',
        weapon_type: 'Disparo',
        damage: '1d12',
        damage_type: 'Perfuração',
        critical: '19',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description:
          'Uma besta pesada, capaz de disparos poderosos. Exige uma ação de movimento para ser recarregada a cada disparo.',
        special: null,
      },
      {
        name: 'Submetralhadora',
        category: 1,
        type: 'Tático',
        weapon_type: 'Arma de fogo',
        damage: '2d6',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 1,
        description: 'Esta arma de fogo automática pode ser empunhada com apenas uma mão.',
        special: null,
      },
      {
        name: 'Espingarda',
        category: 1,
        type: 'Tático',
        weapon_type: 'Arma de fogo',
        damage: '4d6',
        damage_type: 'Balístico',
        critical: '20',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Arma de fogo longa e com cano liso. A espingarda causa apenas metade do dano em alcance médio ou maior.',
        special: null,
      },
      {
        name: 'Fuzil de Assalto',
        category: 2, // Categoria II
        type: 'Tático',
        weapon_type: 'Arma de fogo',
        damage: '2d10',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description: 'A arma de fogo padrão da maioria dos exércitos modernos. É uma arma automática.',
        special: null,
      },
      {
        name: 'Fuzil de Precisão',
        category: 3, // Categoria III
        type: 'Tático',
        weapon_type: 'Arma de fogo',
        damage: '2d10',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Esta arma de fogo de uso militar é projetada para disparos longos e precisos. Se for veterano em Pontaria e mirar com um fuzil de precisão, você recebe +5 na margem de ameaça de seu ataque.',
        special: null,
      },

      // ========== ARMAS PESADAS ==========
      {
        name: 'Bazuca',
        category: 3,
        type: 'Pesado',
        weapon_type: 'Corpo a corpo',
        damage: '10d8',
        damage_type: 'Impacto',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Este lança-foguetes foi concebido como uma arma anti-tanques, mas também se mostrou eficaz contra criaturas. A bazuca causa seu dano no alvo atingido e em todos os seres num raio de 3m; esses seres (mas não o alvo atingido diretamente) têm direito a um teste de Reflexos (DT Agi) para reduzir o dano à metade. Você pode disparar o foguete num ponto qualquer em alcance médio, em vez de num ser específico; nesse caso, não precisa rolar ataque e não tem chance de errar. A bazuca exige uma ação de movimento para ser recarregada a cada disparo.',
        special: null,
      },
      {
        name: 'Lança-chamas',
        category: 3,
        type: 'Pesado',
        weapon_type: 'Corpo a corpo',
        damage: '6d6',
        damage_type: 'Fogo',
        critical: '20',
        critical_multiplier: 'x2',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Equipamento militar que esguicha líquido inflamável incandescente. Atinge todos os seres em uma linha de 1,5m de largura com alcance curto. Faça um único teste de ataque e compare com a Defesa de todos na área. Seres atingidos ficam em chamas.',
        special: null,
      },
      {
        name: 'Metralhadora',
        category: 2, // Categoria II
        type: 'Pesado',
        weapon_type: 'Arma de fogo',
        damage: '2d12',
        damage_type: 'Balístico',
        critical: '19',
        critical_multiplier: 'x3',
        range: 'Corpo a corpo',
        ammo_capacity: null,
        ammo_type: null,
        spaces: 2,
        description:
          'Uma arma de fogo pesada. Para atacar, você precisa ter Força 4 ou maior ou gastar uma ação de movimento para apoiá-la em seu tripé; caso contrário, sofre –5 em seus ataques. É uma arma automática.',
        special: null,
      },
    ]

    for (const w of weapons) {
      await db.table('weapons').insert({
        name: w.name,
        category: w.category,
        type: w.type,
        weapon_type: w.weapon_type,
        damage: w.damage,
        damage_type: w.damage_type,
        critical: w.critical,
        critical_multiplier: w.critical_multiplier,
        range: w.range,
        ammo_capacity: w.ammo_capacity,
        ammo_type: w.ammo_type,
        spaces: w.spaces,
        description: w.description,
        special: w.special,
        created_at: now,
        updated_at: now,
      })
    }

    console.log(`✓ Armas: limpeza e inserção de ${weapons.length} armas concluída.`)
  }
}
